### ISSUE TITLE
Program's saved ppm images are garbled

### ISSUE THREAD

**Issue by TomasBorsje** [TomasBorsje/VirtualAVC#1]
I assume this line of code isn't working on my end:
    takePicture();
    SavePPMFile("i0.ppm",cameraView);
Can anyone confirm if the robot program takes & saves pictures appropriately on their end?
Opening these pictures online or with a ppm viewer shows them as half black / obviously messed up.

**Comment by TomasBorsje** [comment]
https://puu.sh/FUF43/9d24e3fbba.png
Here are some examples of the strange images. The mostly black images are both copies of i0.ppm (created by SavePPMFile) and the static-esque ones are rob.ppm. Not sure what rob.ppm is for.

**Comment by WhiteRose532** [comment]
I couldn't get a viewable picture so you're doing better than me.

**Comment by TomasBorsje** [comment]
Solved!
I simply recompiled the server3.exe and now the robot saves image files properly.
If anyone has this same issue, feel free to reopen this git issue.
